name: ako
description: Ako is a collection of generic Flutter widgets, extensions and utilities.
version: 0.5.0
homepage: https://github.com/AtjonTV
repository: https://github.com/ATVG-Studios/Ako

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  optional: ^6.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
