name: ako_core
description: Ako Core is a collection of generic Flutter widgets, extensions and utilities.
version: 0.9.1
homepage: https://github.com/ATVG-Studios/Ako
repository: https://github.com/ATVG-Studios/Ako

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
