name: ako_map
description: Ako Map is an Ako Core extension module for the OpenStreetMap package
version: 0.1.2
homepage: https://github.com/ATVG-Studios/Ako
repository: https://github.com/ATVG-Studios/Ako

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ako_core: ^0.9.0
  flutter_osm_plugin: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
